//Try Catch


const numero1 = 20;
const numero2 = 30;
const numero3 = 40;

console.log(numero1);

try {
    console.log(numero4);
} catch(error) {
    console.log(error)
}

console.log(numero3);
